# Application Name
spring.application.name=security-backend


spring.datasource.url=jdbc:postgresql://localhost:5432/guardian_security
spring.datasource.username=postgres
spring.datasource.password=N_hummer27
spring.datasource.driver-class-name=org.postgresql.Driver

// JPA / Hibernate Configuration create, update, validate, none
# Force Hibernate to handle schema management based on JPA entities
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

server.port=8080

spring.jpa.show-sql=true 
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

security.jwt.secret-key=4Wn9P7qSUwW51dZbEaGUltkhI+SH4bIIsE1Us/XcOh4=
security.jwt.expiration-time=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nhum5996@gmail.com
spring.mail.password=sazh wyoe frur wggx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379

# Azure IoT Hub Configuration
azure.iothub.eventhub-connection-string=Endpoint=sb://ihsuprodytres003dednamespace.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=2Rlb0/l4pbfYEtmjA8Qnt97mEJtabKct+AIoTJduAZE=;EntityPath=iothub-ehub-guardianse-56011091-2bc65b1b4a
azure.iothub.consumer-group=backend-processor
# Blob storage for checkpoints
azure.storage.checkpoint-connection-string=DefaultEndpointsProtocol=https;AccountName=checkgroup44;AccountKey=jyQGPIfZYH/j3LAIWpJurvcP75XPX0IBahTH923cQXjM8iUQq7X4uCjjzZjrwTA5yAzKhwzx6iZN+AStwcsUtw==;EndpointSuffix=core.windows.net
azure.storage.checkpoint-container=checkpointml44

# Azure Event Hub Configuration
azure.iothub.ehub-connection-string=Endpoint=sb://ihsuprodytres003dednamespace.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=2Rlb0/l4pbfYEtmjA8Qnt97mEJtabKct+AIoTJduAZE=;EntityPath=iothub-ehub-guardianse-56011091-2bc65b1b4a



azure.storage.connection-string=jyQGPIfZYH/j3LAIWpJurvcP75XPX0IBahTH923cQXjM8iUQq7X4uCjjzZjrwTA5yAzKhwzx6iZN+AStwcsUtw==
azure.storage.container-name=checkpointml44