# Application Name
spring.application.name=security-backend


spring.datasource.url=jdbc:postgresql://localhost:5432/guardian_security
spring.datasource.username=postgres
spring.datasource.password=N_hummer27
spring.datasource.driver-class-name=org.postgresql.Driver

// JPA / Hibernate Configuration create, update, validate, none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

server.port=8080

spring.jpa.show-sql=true 
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

security.jwt.secret-key=4Wn9P7qSUwW51dZbEaGUltkhI+SH4bIIsE1Us/XcOh4=
security.jwt.expiration-time=86400000